### ISSUE TITLE
What is the best way to get started with computational geometry?

### ISSUE THREAD

**Issue by abigopal** [mikolalysenko/ama#10]
I'm a mathematics undergraduate and I find your open source work really cool! What resources would you suggest for someone like me, who is interested in the rigorous mathematics side of things but has little experience in geometry, itself? And, what type of projects should I start on to gain competency in the field?

**Comment by mikolalysenko** [comment]
Well, the good news is that if you are just starting out, there are tons of great resources which you can use to get up to speed.  For beginners, one of the best places to start is to read a book.  I recommend any of the following as awesome places to begin:
- M. de Berg, O. Cheong, M. Kreveld, M. Overmars. "[Computational Geometry: Algorithms and Applications](http://www.cs.uu.nl/geobook/)":  A great book for learning the basics of computational geometry.  The chapters are all relatively self contained and motivated, so it is easy to pick up, jump to a random section and start working.  If you haven't had much experience yet with the basics, start here.
- S.L. Devadoss, J. O'Rourke. "[Discrete and computational geometry](http://cs.smith.edu/~orourke/DCG/)":  This follows a more principled and logical progression than de Berg et. al, but covers a much more narrow range of topics.  Notably absent is any discussion of linear programming, point location or range queries, which are all fairly important things to know.  In exchange though, it does go much deeper into the geometry of polytopes which is arguably the true heart of the subject of computational geometry.

It can also be useful to study specific implementations of geometric algorithms to get some idea of how things work in practice.  There are a few really high quality systems out there which are worth studying in some detail to understand how they work and what sorts of subtleties one needs to deal with in the real world when implementing things.  As a starting point, I would highly recommend looking at the following sytems:
- [Triangle](https://www.cs.cmu.edu/~quake/triangle.html), by Jonathan Shewchuk, is the gold standard for 2D triangular mesh generation and Delaunay triangulation.  It is has won numerous awards, including the prestigious J.H. Wilkinson prize for numerical software.  Perhaps more important than the system itself is the work by Shewchuk and Priest on the development of [robust floating point predicates](https://www.cs.cmu.edu/~quake/robust.html), which are more generally useful in all sorts of geometric algorithms.
- [CGAL](http://www.cgal.org/), which is an exhaustive collection of extremely high performance geometry algorithms in C++.  While the implementations in CGAL are world class (and in many cases unsurpassed), it does have some usability issues.  Most methods take pages of C++ template cruft to instantiate, and due to restrictive licensing issues it is difficult to use in open source projects.  Still, it is worth studying the documentation and publications surrounding CGAL as the core technology is still very good.

Finally, you can also take a course!  If you are a student at a university, I am sure that you can find something offered by your CS department.  Try asking around or looking at course listings to see what is available.

**Comment by abigopal** [comment]
Thank you so much for the answer! I will get to work, haha. :)

**Comment by w8r** [comment]
thanks!

**Comment by ralphtheninja** [comment]
_drewls over the youtube course_ Thanks! :heart:
