### ISSUE TITLE
Publications in Computer Science

### ISSUE THREAD

**Issue by mattdesl** [mikolalysenko/ama#9]
Specifically what do you feel about these issues:

1.
Should knowledge/publications be hidden behind a paywall?

2.
Why do so many programming-related publications not provide source code? Or, when code _is_ provided, it is often just fragments, with so many details left out that it becomes difficult or impossible to reproduce the results of the publication to the same degree of performance. Whereas in most other fields of science, reproducibility is encouraged and expected.

3.
I feel there is a massive disconnect between researchers (writing the papers) and industry programmers, hobbyists and tinkerers (often, the ones trying to implement the papers). What can we do to improve the situation and minimize this gap?

4.
How long before academic research becomes comfortable with small and focused dependencies, eg. npm modules? Often the amount of boilerplate code from academic research is staggering, and you end up sifting through a lot of "NIH" (i.e. OpenGL bindings, matrix math, OBJ parsing) just to find the actual guts of the research.

**Comment by mikolalysenko** [comment]
A couple of questions here, but I'll answer them individually:

1.
Obviously not.  The current academic publishing industry is corrupt and parasitic.  Reviewers, editors and authors work for free while bloated and useless publishers like Elsevier collect rent.  The only reason this still exists is because the incentive structures built into academia require publishing at exclusive journals whose brands carry a large amount of prestige.  Many alternatives like OpenAccess journals also tend to be scams which shift costs from the reader to the author.

2.
For most academics, they have no incentive to do so.  Publishing code isn't gonna make reviewers more likely to accept their paper, and it gets them no points with the tenure committees to whom they are ultimately accountable.  Publishing and maintaining code is a huge time and resource sink for a small lab, so it is generally easier to just knock out a proof of concept, write it up, then get on to the next thing as quickly as possible.  Not to mention that these things get stale if left in the open air for too long, and that there is little if any career value to maintaining them.

3.
By their nature academic communities are often very exclusive, as in some sense their purpose is to concentrate knowledge.  In order to get access to what is really going on at the high levels in academia, you either have to go through the ringer of graduate school or else buy your way in (usually by visiting expensive conferences, purchasing journal subscriptions or setting up projects with various professors). 

On the flip side though, I do think that industry programmers and hobbyists need to step up their game a bit.  In the open source world, there is a lack of rigor and also not much effort made to acknowledge prior art, so you get a lot of people repeating the same sorts of mistakes.  Today, with the internet and Google scholar you can get access to many of the same resources that would be available to a researcher at a well funded institution and so there isn't much excuse anymore for not doing your homework.

4.
I actually find that this problem isn't nearly as bad in academics as in industry!  In academic programming, you tend to see code written by less experienced programmers more frequently but it tends to be horrible in different ways. For example, reinventing OpenGL bindings/matrix math/etc. is generally looked down upon by most researchers as low level and pointless tinkering (though it may be tolerated if it is helpful in educating a student).  

On the other hand, what I have seen is that academic programmers tend to adopt a get-it-done-quick-as-possible mentality and are also more willing to wantonly grab huge dependencies or copy-paste and then tweak big projects.  The unfortunate thing though is that these dependencies are often not managed, so you usually end up with horrible mutated blobs of MATLAB, FORTRAN, C++ and Python all duct-taped together with Perl scripts.  See for example the widely used [bundler project](http://www.cs.cornell.edu/~snavely/bundler/) which solves structure-from-motion.  Setting it up is practically a trade secret (I had to learn from my computer vision professor)!
